### ISSUE TITLE
I'm anticipating default version ！

### ISSUE THREAD

**Issue by kickassa** [romeno-moreno/mxmrig#2]
I don't even know how to use this monerocean pool,and their official website doesn't show anything either.

**Comment by swannes** [comment]
Look into the help section of MoneroOcean, It is just as any other pool. You can mine withe the default client and only mine for XMR. You can connect with their client, and have algorithm switching (so you mine for other, more profitable coins) but get paid in XMR.

**Comment by zhjyz2** [comment]
I don't like the moneroocean pool, I can only mine as xmr there. I'd like to pay with various coins, but I know that the xmrig of the moneroocean version works differently with the normal one. We need the default version!

**Comment by cnle** [comment]
We need the default version!
When will the default version be released?
Also I found that the website xmrig.com has failed.

**Comment by romeno-moreno** [comment]
Unfortunately, I'm no longer supporting the project and no new versions will be released 😞

**Comment by romeno-moreno** [comment]
Unfortunately, I'm no longer supporting the project and no new versions will be released 😞
